---
- name: Init docker swarm
  docker_swarm:
    state: present
    api_version: 1.43
  register: init_swarm

- name: join
  set_fact:
    join_token_worker: "{{ init_swarm.swarm_facts.JoinTokens.Worker }}"
